=== urekha20/proj1/sap/BD_NW_7.0_Presentation_7.40_Comp._1_/PRES1/BI_PreCalServer/Setup/ProductVars.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SapSetup (Variable*)+>
<!ATTLIST SapSetup
	Context (Init | Server | Workstation | Patch | Variables) #REQUIRED
	Version CDATA #IMPLIED
>
<!ELEMENT Variable (Value+)+>
<!ATTLIST Variable
	Name CDATA #REQUIRED
	Persistent (TRUE | FALSE) #IMPLIED
	ConnectedId CDATA #IMPLIED
	Description CDATA #IMPLIED
	DisplayInSapAdmin (TRUE | FALSE) #IMPLIED
>
<!ELEMENT Value (#PCDATA)>
<!ATTLIST Value
	Script (TRUE | FALSE) #IMPLIED
>

=== urekha20/proj1/sap/BD_NW_7.0_Presentation_7.40_Comp._1_/PRES1/BI_PreCalServer/Setup/SapSetupVars.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SapSetup SYSTEM "../Setup/ProductVars.dtd">
<SapSetup Context="Variables" Version="900.15">
    <Variable Name="SapSetupDir" Persistent="true">
        <Value>%ProgramFiles%\SAP\SAPsetup</Value>
    </Variable>
    <Variable Name="CabFilesSrcDir" Persistent="false">
        <Value>%SapSrcDir%\CAB</Value>
    </Variable>
    <Variable Name="WinWordExist" Persistent="false">
        <Value>NO</Value>
        <Value Script="true"><![CDATA[
NWEngine.Context.Log.Write "Script: Checking for WinWord..."
If NWEngine.Shell.RegKeyExist("HKCR\Word.Document.8\shell\open\command") Then
  NWEngine.Variables.AppendDefaultValue "WinWordExist", "YES"
End If
NWEngine.Variables.Persistent( "WinWordExist" ) = vbFalse
      ]]></Value>
    </Variable>
    <Variable Name="CommonStartUpGroup" Persistent="false">
        <Value>C:\UNDEFINED</Value>
        <Value Script="true"><![CDATA[
szBuffer  = ""
szRegKey  = "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders"
szRegName = szRegKey & "\Common Startup"
If NwEngine.Shell.RegKeyExist( szRegKey ) Then
        szPath = NwEngine.Shell.GetRegValue( szRegName )
        NwEngine.Context.Log.Write "Startup folder = " & Chr(34) & szPath & Chr(34)
        iPos = InstrRev( szPath, "\" )
        szBuffer = mid( szPath, iPos + 1 )
End if
NWEngine.Variables.AppendDefaultValue "CommonStartUpGroup", szBuffer
      ]]></Value>
    </Variable>
    <Variable Name="JdkHome" Persistent="false">
        <Value>C:\UNDEFINED</Value>
        <Value Script="true"><![CDATA[
IsJdkMissing()

Function IsJdkMissing()
        IsJdkMissing = vbFalse ' default
        bJdkExists = vbFalse
        strJdkHome = ""
        strJavaExe = ""
        NWEngine.Context.Log.Write "Variables-Script: Checking for JDK HOME"
        If bSearchForJavaMinorVersion( "1.5.0" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaHome( "1.5", "" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.4.2" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.4.1" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaHome( "1.4", "" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.3.1" ) Then
                bJdkExists = vbTrue
        ElseIf bSearchForJavaHome( "1.3", "" ) Then
                bJdkExists = vbTrue
        Else
                bJdkExists = vbFalse
        End If
        If Not bJdkExists Then
                NWEngine.Context.Log.WriteWarning "Variables-Script: JDK could not be detected!"
                IsJdkMissing = vbTrue
        End If
End Function

Function bSearchForJavaMinorVersion( szMajorVersion )
        bSearchForJavaMinorVersion = vbFalse
        iMinorVersion = 19
        Do While iMinorVersion > 0
                szMinorVersion = "0" & iMinorVersion
                If bSearchForJavaHome( szMajorVersion, szMinorVersion ) Then
                        bSearchForJavaMinorVersion = vbTrue
                        Exit Function
                Else
                        iMinorVersion = iMinorVersion - 1
                End If
        Loop
        If bSearchForJavaHome( szMajorVersion, "" ) Then
                bSearchForJavaMinorVersion = vbTrue
        End If
End Function

Function bSearchForJavaHome( szMajorVersion, szMinorVersion )
        bSearchForJavaHome = vbFalse
        If szMajorVersion = "1.3" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.3"
        ElseIf szMajorVersion = "1.4" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.4"
        ElseIf szMajorVersion = "1.5" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.5"
        Else
                If szMinorVersion = "" Then
                        strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Development Kit\" & szMajorVersion
                Else
                        strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Development Kit\" & szMajorVersion & "_" & szMinorVersion
                End If
        End If
        strJavaHomeEntry = strVersionKey & "\JavaHome"
        If NWEngine.Shell.RegKeyExist( strVersionKey ) Then
                strJdkHome = NWEngine.Shell.GetRegValue( strJavaHomeEntry )
                If strJdkHome <> "" Then
                        strJavaExe = strJdkHome & "\bin\java.exe"
                        NWEngine.Context.Log.Write "Scriptlet : Searching for " & strJavaExe & " ..."
                        If NWEngine.Shell.FileExist( strJavaExe ) Then
                                NWEngine.Context.Log.Write "Scriptlet : Java Development Kit detected."
                                bSearchForJavaHome = vbTrue
                                NWEngine.Variables.AppendDefaultValue "JdkHome", strJdkHome
                        End If
                End If
        End If
End Function
      ]]></Value>
    </Variable>
    <Variable Name="JreHome" Persistent="false">
        <Value>C:\UNDEFINED</Value>
        <Value Script="true"><![CDATA[
IsJreMissing()

Function IsJreMissing()
        IsJreMissing = vbFalse ' default
        bJreExists = vbFalse
        strJreHome = ""
        strJavaExe = ""
        NWEngine.Context.Log.Write "Variables-Script: Checking for Jre HOME"
        If bSearchForJavaMinorVersion( "1.5.0" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaHome( "1.5", "" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.4.2" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.4.1" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaHome( "1.4", "" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaMinorVersion( "1.3.1" ) Then
                bJreExists = vbTrue
        ElseIf bSearchForJavaHome( "1.3", "" ) Then
                bJreExists = vbTrue
        Else
                bJreExists = vbFalse
        End If
        If Not bJreExists Then
                NWEngine.Context.Log.WriteWarning "Variables-Script: JRE could not be detected!"
                IsJreMissing = vbTrue
        End If
End Function

Function bSearchForJavaMinorVersion( szMajorVersion )
        bSearchForJavaMinorVersion = vbFalse
        iMinorVersion = 19
        Do While iMinorVersion > 0
                szMinorVersion = "0" & iMinorVersion
                If bSearchForJavaHome( szMajorVersion, szMinorVersion ) Then
                        bSearchForJavaMinorVersion = vbTrue
                        Exit Function
                Else
                        iMinorVersion = iMinorVersion - 1
                End If
        Loop
        If bSearchForJavaHome( szMajorVersion, "" ) Then
                bSearchForJavaMinorVersion = vbTrue
        End If
End Function

Function bSearchForJavaHome( szMajorVersion, szMinorVersion )
        bSearchForJavaHome = vbFalse
        If szMajorVersion = "1.3" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\1.3"
        ElseIf szMajorVersion = "1.4" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\1.4"
        ElseIf szMajorVersion = "1.5" Then
                strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\1.5"
        Else
                If szMinorVersion = "" Then
                        strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\" & szMajorVersion
                Else
                        strVersionKey = "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment\" & szMajorVersion & "_" & szMinorVersion
                End If
        End If
        strJavaHomeEntry = strVersionKey & "\JavaHome"
        If NWEngine.Shell.RegKeyExist( strVersionKey ) Then
                strJreHome = NWEngine.Shell.GetRegValue( strJavaHomeEntry )
                If strJreHome <> "" Then
                        strJavaExe = strJreHome & "\bin\java.exe"
                        NWEngine.Context.Log.Write "Scriptlet : Searching for " & strJavaExe & " ..."
                        If NWEngine.Shell.FileExist( strJavaExe ) Then
                                NWEngine.Context.Log.Write "Scriptlet : Java Runtime Environment detected."
                                bSearchForJavaHome = vbTrue
                                NWEngine.Variables.AppendDefaultValue "JreHome", strJreHome
                        End If
                End If
        End If
End Function
      ]]></Value>
    </Variable>
    <Variable Name="Jre6Version" Persistent="false">
        <Value>0.0.0.0</Value>
    </Variable>
    <Variable Name="Jre6Home" Persistent="false">
        <Value>UNDEFINED</Value>
        <Value Script="true"><![CDATA[
                                Option Explicit
                                NwEngine.Context.Log.Write "Script JRE6x86: Checking if Oracle JRE 1.6.0 (32 Bit) is installed"
                                If NwEngine.Shell.RegValueExist("HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\Java6FamilyVersion") Then
                                        Dim szJre6Version
                                        szJre6Version = NwEngine.Shell.GetRegValue("HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\Java6FamilyVersion")
                                        NwEngine.Context.Log.Write "Script JRE6x86: Found Oracle JRE in version " & szJre6Version
                                        Dim strUnderscorePos
                                        strUnderscorePos = InStrRev(szJre6Version, "_", -1, 1 )
                                        Dim strJavaUpdate
                                        If strUnderscorePos > 0 Then
                                                strJavaUpdate = Mid (szJre6Version, strUnderscorePos + 1 )
                                        Else
                                                strJavaUpdate = 0
