=== urekha20/proj1/sap/BD_NW_7.0_Presentation_7.40_Comp._1_/PRES1/BI_PreCalServer/Setup/ProductLocales.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SapSetup (String*)+>
<!ATTLIST SapSetup
	Context (Init | Server | Workstation | Patch | Locale) #REQUIRED
	DatabaseVersion CDATA #IMPLIED
	Version CDATA #IMPLIED
>
<!ELEMENT String (En+ | De*)+>
<!ATTLIST String
	Name CDATA #REQUIRED
>
<!ELEMENT En (#PCDATA)>
<!ELEMENT De (#PCDATA)>

=== urekha20/proj1/sap/BD_NW_7.0_Presentation_7.40_Comp._1_/PRES1/BI_PreCalServer/Setup/SapSetupLocale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SapSetup SYSTEM "../Setup/ProductLocales.dtd">
<SapSetup Context="Locale" Version="900.5">
  <!-- Wiz Ui General -->
  <String Name="StrWindowCaption">
    <En>SAP Front End Installer</En>
    <De>SAP Front-End Installer</De>
  </String>
  <String Name="StrBtnNext">
    <En><![CDATA[&Next >]]></En>
    <De><![CDATA[&Weiter >]]></De>
  </String>
  <String Name="StrBtnCheck">
    <En><![CDATA[Chec&k >]]></En>
    <De><![CDATA[&Prüfen >]]></De>
  </String>
  <String Name="StrBtnVerify">
    <En><![CDATA[&Verify]]></En>
    <De><![CDATA[&Verifizieren]]></De>
  </String>
  <String Name="StrBtnBack">
    <En><![CDATA[< &Back]]></En>
    <De><![CDATA[< Zurück]]></De>
  </String>
  <String Name="StrBtnFinish">
    <En>Done</En>
    <De>Fertig</De>
  </String>
  <String Name="StrBtnBrowse">
    <En>Browse</En>
    <De>Suchen</De>
  </String>
  <String Name="StrBtnCancel">
    <En>Cancel</En>
    <De>Abbrechen</De>
  </String>
  <String Name="StrBtnClose">
    <En>Close</En>
    <De>Beenden</De>
  </String>
  <String Name="StrBtnShare">
    <En>Share</En>
    <De>Freigeben</De>
  </String>
  <String Name="StrBtnIgnore">
    <En><![CDATA[Ignore >]]></En>
    <De><![CDATA[Ignorieren >]]></De>
  </String>
  <String Name="StrVerificationSuccess">
    <En>Verification successful. Choose "Next".</En>
    <De>Verifikation erfolgreich. Wählen Sie "Weiter".</De>
  </String>
  <String Name="StrVerificationFailRecommendReboot">
    <En>A reboot is pending for the specified computer. It is strongly recommended that you first reboot the relevant computer before continuing.</En>
    <De>Der angegebene Computer muss neu gestartet werden. Führen Sie dies zuvor aus.</De>
  </String>
  <String Name="StrVerificationFailInvalidPath">
    <En>The specified path is not valid or does not exist.</En>
    <De>Der angegebene Pfad ist ungültig oder nicht vorhanden.</De>
  </String>
  <String Name="StrVerificationFailAccessDenied">
    <En>Access to the specified path is denied.</En>
    <De>Zugriff auf den angegebenen Pfad ist nicht möglich.</De>
  </String>
  <String Name="StrVerificationFailSharedDenied">
    <En>Access to the specified UNC path is denied.</En>
    <De>Zugriff auf den angegeben UNC-Pfad ist nicht möglich.</De>
  </String>
  <String Name="StrVerificationFailNotAServerPath">
    <En>The specified path is not a valid installation server.</En>
    <De>Der angegebene Pfad ist kein Installationsserver.</De>
  </String>
  <String Name="StrVerificationUserNameEmpty">
    <En>Enter the user name.</En>
    <De>Benutzernamen eingeben.</De>
  </String>
  <String Name="StrVerificationPasswordEmpty">
    <En>Enter password</En>
    <De>Passwort eingeben</De>
  </String>
  <String Name="StrVerificationPasswordsDiffer">
    <En>The passwords do not match.</En>
    <De>Die eingegebenen Passwörter sind verschieden.</De>
  </String>
  <String Name="CancelConfirmationMsg">
    <En>Do you really want to abort the installation process?</En>
    <De>Möchten Sie die Installation wirklich abbrechen?</De>
  </String>
  <String Name="StrPackageIsIncomplete">
    <En><![CDATA[<font color="Red">This package cannot be installed as it is incomplete on the installation source.</font>]]></En>
    <De><![CDATA[<font color="Red">Dieses Paket kann nicht installiert werden, da es nicht vollständig in der Installationsquelle vorhanden ist.</font>]]></De>
  </String>
  <String Name="StrPackageIsDisabled">
    <En><![CDATA[<font color="Red">Not all package prerequisits are fulfilled.</font>]]></En>
    <De><![CDATA[<font color="Red">Nicht alle Voraussetzungen für dieses Paket sind erfüllt.</font>]]></De>
  </String>
  <String Name="StrRequiredNodeDeselected">
    <En><![CDATA[<font color="Red">Product %PRODUCTNODE% is no longer required and will be uninstalled.</font>]]></En>
    <De><![CDATA[<font color="Red">Produkt %PRODUCTNODE% wird nicht mehr benötigt und wird deinstalliert.</font>]]></De>
  </String>
  <String Name="StrExcludedNodeDeselected">
    <En><![CDATA[<font color="Red">Product %PRODUCTNODE% is incompatible with a product that is being updated and will be uninstalled.</font>]]></En>
    <De><![CDATA[<font color="Red">Produkt %PRODUCTNODE% ist inkompatibel mit einem neueren Produkt und wird deinstalliert.</font>]]></De>
  </String>
  <String Name="StrExcludedNodeCantBeDeselected">
    <En><![CDATA[<font color="Red">Product %PRODUCTNODE% is incompatible with a product that is being updated but it cannot be uninstalled.</font>]]></En>
    <De><![CDATA[<font color="Red">Produkt %PRODUCTNODE% ist inkompatibel mit einem neueren Produkt, kann aber nicht deinstalliert werden.</font>]]></De>
  </String>
  <String Name="StrExcludedNodeCantBeUpdated">
    <En><![CDATA[<font color="Red">The new version of product %PRODUCTNODE% is incompatible with an installed product. Update will be skipped.</font>]]></En>
    <De><![CDATA[<font color="Red">Die neue Version von Produkt %PRODUCTNODE% ist inkompatibel mit einem installierten Produkt. Die neue Version wird nicht installiert.</font>]]></De>
  </String>

  <String Name="RebootBalloonTitle">
    <En>Confirm Reboot</En>
    <De>Neustart bestätigen</De>
  </String>
  <String Name="RebootBalloonText">
    <En>Click this button to reboot your computer now.</En>
    <De>Klicken Sie hier, um den Computer neu zu starten.</De>
  </String>
  <String Name="RebootMachineBalloonText">
    <En>Click this button to reboot %MACHINE% now.</En>
    <De>Klicken Sie hier, um den Computer %MACHINE% neu zu starten.</De>
  </String>
  <String Name="StrReboot">
    <En>Reboot</En>
    <De>Neustart</De>
  </String>
  <String Name="StrRebootMachine">
    <En>Reboot %MACHINE%</En>
    <De>Neustart von %MACHINE%</De>
  </String>
  <String Name="StrBtnReboot">
    <En>Reboot Now</En>
    <De>Neustart</De>
  </String>
  <String Name="RebootMessage">
    <En>System reboot for completion of an installation procedure initiated.</En>
    <De>System wird neu gestartet, um eine Installation fertig zu stellen.</De>
  </String>


  <!--Message Page -->
  <String Name="StrMessageTitle">
    <En>Information</En>
    <De>Information</De>
  </String>

  <String Name="StrMessageDescription">
    <En>Error message</En>
    <De>Fehlermeldung</De>
  </String>
  <String Name="strOverrideConditionFailureOnLSH">
    <En><![CDATA[<a style="color:red;">Item cannot be installed because of failing prerequisites. Contact your administrator.</a>]]></En>
    <De><![CDATA[<a style="color:red;">Diese Komponente kann wegen fehlender Installationsvoraussetzung nicht installiert werden. Kontaktieren Sie ihren Administrator.</a>]]></De>
  </String>
  <String Name="strLinkClickToCopy">
    <En>Copy to clipboard</En>
    <De>In die Zwischenablage kopieren</De>
  </String>
  <String Name="StrMsgProductInvalid">
    <En>The specified product is not available.</En>
    <De>Das angegebene Produkt ist nicht verfügbar.</De>
  </String>

  <!--Welcome Page -->

  <String Name="StrWelcomeTitle">
    <En>Welcome to the SAP Front End Installation Wizard</En>
    <De>Willkommen zum SAP Front-End Installationsassistenten</De>
  </String>
  <String Name="StrWelcomeSubTitle">
    <En>Copyright 2002-2011 SAP AG. All Rights Reserved</En>
    <De>Copyright 2002-2011 SAP AG. Alle Rechte vorbehalten</De>
  </String>
  <String Name="StrWelcomeDescription">
    <En>This wizard helps you to configure your SAP Front End installation. Close all SAP applications and press 'Next' to continue.</En>
    <De>Dieser Assistent führt Sie durch die Konfiguration ihrer SAP Front-End Installation. Schließen Sie alle SAP Anwendungen und wählen Sie 'Weiter', um fortzufahren.</De>
  </String>
  <String Name="StrWelcomeUninstallDescription">
    <En>will be uninstalled completely. Close all SAP applications. Press 'Next' to start the uninstallation process.</En>
    <De>wird vollständig deinstalliert. Schließen Sie alle SAP Anwendungen. Wählen Sie 'Weiter', um die Deinstallation zu starten.</De>
  </String>
  <String Name="StrWelcomeFailedUninstall">
    <En>The command line parameter /uninstall must always be accompanied by /product or /package.</En>
    <De>Der Kommandozeilenparameter /uninstall muss immer zusammen mit /product oder /package angegeben werden.</De>
  </String>
  <String Name="StrWelcomePageFailedRepair">
    <En>The repair process cannot be carried out.</En>
    <De>Die Reparatur kann nicht durchgeführt werden.</De>
  </String>
  <String Name="StrWelcomeFailedProductDescription">
    <En>The specified product is not available:</En>
    <De>Das angegebene Produkt ist nicht vorhanden:</De>
  </String>
  <String Name="StrWelcomeFailedPackageDescription">
    <En>The specified package is not available:</En>
    <De>Das angegebene Paket ist nicht vorhanden:</De>
  </String>
  <String Name="StrRebootRecommended">
    <En>A reboot is pending for your system. It is recommended to reboot before continuing.</En>
    <De>Ein Neustart für Ihr System steht aus. Sie sollten den Computer neu starten, bevor Sie fortfahren.</De>
  </String>
  <String Name="StrRebootOnFinishRecommended">
    <En>Reboot your computer now to complete the process.</En>
    <De>Starten Sie den Computer neu, um die Konfiguration abzuschließen.</De>
  </String>
  <String Name="StrRebootOtherMachineRecommended">
    <En>Reboot the computer %MACHINE% now to complete the process.</En>
    <De>Starten Sie den Computer %MACHINE% neu, um die Konfiguration abzuschließen.</De>
  </String>

  <!--Welcome Page : Modifications for local Patching -->
  <String Name="PatchWelcomeTitle">
    <En>Welcome to the SAP Front End patch wizard</En>
    <De>Willkommen zum SAP Front-End Patch Assistenten</De>
  </String>

  <String Name="PatchWelcomeDescription">
    <En>This SAP Front End patch is ready to install. Close all SAP applications and press 'Next' to continue.</En>
    <De>Dieser SAP Front-End Patch ist bereit zur Installation. Schließen Sie alle SAP Anwendungen und wählen Sie 'Weiter'.</De>
  </String>
